// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3BMIC4BUnvEB5pb5wRNJIRHzBofPyix8',
    appId: '1:1010957071784:web:874823073af0b6d1eb199d',
    messagingSenderId: '1010957071784',
    projectId: 'mightyhollowblocks',
    authDomain: 'mightyhollowblocks.firebaseapp.com',
    storageBucket: 'mightyhollowblocks.firebasestorage.app',
    measurementId: 'G-QR5EJQGS2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANkjabqtXoOvuDfyRrDwZwusQsFye_QTY',
    appId: '1:1010957071784:android:dd9a6b673a343760eb199d',
    messagingSenderId: '1010957071784',
    projectId: 'mightyhollowblocks',
    storageBucket: 'mightyhollowblocks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCJxXGp1RohvpOFMBYaxhhU7TtINNRMaY',
    appId: '1:1010957071784:ios:4717048c0e6b1295eb199d',
    messagingSenderId: '1010957071784',
    projectId: 'mightyhollowblocks',
    storageBucket: 'mightyhollowblocks.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCJxXGp1RohvpOFMBYaxhhU7TtINNRMaY',
    appId: '1:1010957071784:ios:4717048c0e6b1295eb199d',
    messagingSenderId: '1010957071784',
    projectId: 'mightyhollowblocks',
    storageBucket: 'mightyhollowblocks.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3BMIC4BUnvEB5pb5wRNJIRHzBofPyix8',
    appId: '1:1010957071784:web:a209d49590f67173eb199d',
    messagingSenderId: '1010957071784',
    projectId: 'mightyhollowblocks',
    authDomain: 'mightyhollowblocks.firebaseapp.com',
    storageBucket: 'mightyhollowblocks.firebasestorage.app',
    measurementId: 'G-MVLXBPWDJR',
  );

}